jwt:
  secretKey: "This Data Must Be Managed By Secret NOT HERE THIS IS JUST EXAMPLE"

log:
  serverName: "Api Server"
  level: ERROR
  slack:
    enabled: true
    webHookUrl: "slack webhook URL"
    channel: error-report-bot
    userName: "[API]ErrorReportBot"
  database:
    enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testDB?serverTimezone=Asia/Seoul
    username: test
    password: test